/* qunix - A minimal Unix-like Kernel
 * Copyright (C) 2026 - 2027 Yixiang Qiu. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _ASM_X86_IRQ_H_
#define _ASM_X86_IRQ_H_

/*
 * qunix interrupt vector layout
 *
 * There are 256 interrupt entries in IDT, This file is the layout and design of
 * the interrupt vectors. It include the interrupts (asynchronous interrupts
 * generated by hardware), exception (synchronous interrupts generated by CPU)
 * and the system calls.
 *
 * The layout is as follows:
 *   Vector  0x00 - 0x1F: CPU fault, trap, abort (Intel defined)
 *   Vector  0x20 - 0x2F: IRQs from 8259 PIC
 *   Vector  0x30 - 0x8F: Available for external interrupts
 *   Vector  0x90       : System calls
 *   Vector  0x91 - 0xFF: Reserved
 */

#define X86_EXC_BASE 0x00 /* Base of exception */
#define X86_EXC_NR 0x20   /* Number of exception */

/* Exception vectors (synchronous interrupts generated by CPU) */

#define X86_EXC_DIVIDE 0x00 /* Divide error */
#define X86_EXC_DEBUG 0x01  /* Debug exception */
#define X86_EXC_NMI 0x02    /* Non-maskable interrupt */
#define X86_EXC_BRKPT 0x03  /* Breakpoint */
#define X86_EXC_OFLOW 0x04  /* Overflow */
#define X86_EXC_BOUND 0x05  /* Bounds check */
#define X86_EXC_ILLOP 0x06  /* Invalid opcode */
#define X86_EXC_DEVICE 0x07 /* Device not available */
#define X86_EXC_DBLFLT 0x08 /* Double fault */
#define X86_EXC_COPROC                                                         \
    0x09 /* Coprocessor segment overrun, reserved not used since 486 */
#define X86_EXC_TSS 0x0A      /* Invalid task switch segment */
#define X86_EXC_SEGNP 0x0B    /* Segment not present */
#define X86_EXC_STACK 0x0C    /* Stack exception */
#define X86_EXC_GPFLT 0x0D    /* General protection fault */
#define X86_EXC_PGFLT 0x0E    /* Page fault */
#define X86_EXC_RESERVED 0x0F /* Reserved */
#define X86_EXC_FPERR 0x10    /* x87 FPU floating point error */
#define X86_EXC_ALIGN 0x11    /* Alignment check */
#define X86_EXC_MCHK 0x12     /* Machine check */
#define X86_EXC_SIMDERR 0x13  /* SIMD floating point error */
#define X86_EXC_VIRT 0x14     /* Virtualization exception */
#define X86_EXC_SECURITY 0x1E /* Security exception */

/* IRQ vectors (asynchronous interrupts generated by hardware) */

#define X86_IRQ_BASE 0x20 /* Base of IRQs */
#define X86_IRQ_NR 0x10   /* Number of IRQs */

#define IRQ_NR X86_IRQ_NR /* Number of interrupt lines */

#define X86_IRQ_TIMER 0x00   /* timer */
#define X86_IRQ_KBD 0x01     /* keyboard */
#define X86_IRQ_CASCADE 0x02 /* cascade (used for slave PIC)*/
#define X86_IRQ_COM2 0x03    /* COM2 */
#define X86_IRQ_COM1 0x04    /* COM1 */
#define X86_IRQ_LPT2 0x05    /* LPT2 */
#define X86_IRQ_FLOPPY 0x06  /* floppy disk */
#define X86_IRQ_LPT1 0x07    /* LPT1 / unreliable error */
#define X86_IRQ_CMOS 0x08    /* CMOS real-time clock */
#define X86_IRQ_AVAL1 0x09   /* available IRQ 1 */
#define X86_IRQ_AVAL2 0x0A   /* available IRQ 2 */
#define X86_IRQ_AVAL3 0x0B   /* available IRQ 3 */
#define X86_IRQ_PS2M 0x0C    /* PS2 mouse */
#define X86_IRQ_FPU 0x0D     /* FPU / Coprocessor */
#define X86_IRQ_ATA 0x0E     /* Primary ATA hard disk */
#define X86_IRQ_ATA2 0x0F    /* Secondary ATA hard disk */

#define X86_SYSCALL 0x90 /* System call */

#endif /* _ASM_X86_IRQ_H_ */